### ISSUE TITLE
missing dream_jobs.txt

### ISSUE THREAD

**Issue by suryacosm** [hunter-college-ossd-fall-2019/NVA-workflow#4]
Should contain, for each team member, a description of dream job that the team member would like to get after graduation.

**Comment by yoonboyeong** [comment]
nancydocode(nancy): software engineer / What about you guys @Aleks118 @vioelsdm

**Comment by Aleks118** [comment]
Game developer

**Comment by yoonboyeong** [comment]
- [x] Aleks: Game Developer
- [x] Nancy: Software Engineer
- [ ] Roy? Rio?:

**Comment by ValeroM** [comment]
I think you tagged me incorrectly. I'm marco Valero. I'm in some other
team.
